development:
  adapter: mysql2
  database: inventory_dev
  username: rails_user
  password: 5yn3x@_2001
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
  #port: 3306

test:
  adapter: mysql2
  database: inventory_test
  username: test_user
  password: 5yn3x@_2001
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
  #port: 3306

production:
  adapter: mysql2
  database: inventory_prod
  username: rails_user
  password: 5yn3x@_2001
  host: localhost
  socket: /run/mysqld/mysqld.sock
